name: Deploy all services to VM (CD)
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Migrate
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.migrate 
          push: true
          tags: | 
            ritikaxg/migrate:${{ github.sha }}
            ritikaxg/migrate:latest
          build-args: |
            ENV_FILE=.env.compose

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.backend
          push: true
          tags: | 
            ritikaxg/backend:${{ github.sha }}
            ritikaxg/backend:latest
          build-args: |
            ENV_FILE=.env.compose

      - name: Build and Push WS
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.ws 
          push: true
          tags: | 
            ritikaxg/ws:${{ github.sha }}
            ritikaxg/ws:latest
          build-args: |
            ENV_FILE=.env.compose

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.frontend 
          push: true
          tags: |
            ritikaxg/frontend:${{ github.sha }}
            ritikaxg/frontend:latest
          build-args: |
            ENV_FILE=.env.compose
            DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres

      - name: SSH and Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Deploy-monorepo-cicd-docker
            git pull origin main

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d



